version: '3.8'

services:
  app:
    container_name: node-hello-world-app
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      NODE_ENV: production