name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: 'backend/package-lock.json'
        
    - name: Install dependencies
      working-directory: backend
      run: npm ci
      
    - name: Lint code
      working-directory: backend
      run: npm run lint
      
    - name: Run unit tests
      working-directory: backend
      run: npm run test:unit
      
    - name: Run integration tests
      working-directory: backend
      run: npm run test:integration
      
    - name: Run E2E tests
      working-directory: backend
      run: npm run test:e2e
      
    - name: Generate coverage report
      working-directory: backend
      run: npm run test:coverage